// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg1hc84aInkY5pSIN8m956GgunMjNmOkA',
    appId: '1:226593045547:web:3bfc0c13f6bd6416897e6e',
    messagingSenderId: '226593045547',
    projectId: 'smart-currency-fdc28',
    authDomain: 'smart-currency-fdc28.firebaseapp.com',
    storageBucket: 'smart-currency-fdc28.firebasestorage.app',
    measurementId: 'G-W0J1NS3H8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWr76skKPAeMDyixtyErxQKl40HfAOWGM',
    appId: '1:226593045547:android:f5258ebecb39a120897e6e',
    messagingSenderId: '226593045547',
    projectId: 'smart-currency-fdc28',
    storageBucket: 'smart-currency-fdc28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS6LZql-QrzgZKUGNRUr05gQljUTbpkII',
    appId: '1:226593045547:ios:037b652ac3a9088b897e6e',
    messagingSenderId: '226593045547',
    projectId: 'smart-currency-fdc28',
    storageBucket: 'smart-currency-fdc28.firebasestorage.app',
    iosBundleId: 'com.calculate.smartCurrency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS6LZql-QrzgZKUGNRUr05gQljUTbpkII',
    appId: '1:226593045547:ios:359d39ea5eb8ab79897e6e',
    messagingSenderId: '226593045547',
    projectId: 'smart-currency-fdc28',
    storageBucket: 'smart-currency-fdc28.firebasestorage.app',
    iosBundleId: 'com.example.smartCurrency',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg1hc84aInkY5pSIN8m956GgunMjNmOkA',
    appId: '1:226593045547:web:4fc7f1e42b10a4f9897e6e',
    messagingSenderId: '226593045547',
    projectId: 'smart-currency-fdc28',
    authDomain: 'smart-currency-fdc28.firebaseapp.com',
    storageBucket: 'smart-currency-fdc28.firebasestorage.app',
    measurementId: 'G-XK2VQP35E9',
  );
}
